/**
 * PDF accessibility report generation using jsPDF.
 * Dynamically imports jspdf to avoid loading the library until needed.
 */

import { formatRatio, type WCAGResults } from './contrastCalculation';

export interface ReportData {
  projectName: string;
  notes: string;
  fg: string;
  bg: string;
  ratio: number;
  wcag: WCAGResults;
}

/**
 * Generate a PDF report. Returns a Blob URL for download.
 * Uses dynamic import so jspdf only loads when needed.
 */
export async function generateReport(data: ReportData): Promise<void> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const pageW = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentW = pageW - margin * 2;
  let y = margin;

  // Helper to add page if needed
  const checkPage = (needed: number): void => {
    if (y + needed > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
  };

  // ---- Page 1: Cover ----
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text('Accessibility Color Report', margin, y + 20);
  y += 30;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by accessibilitycolor.com', margin, y);
  y += 8;
  doc.text(`Date: ${new Date().toLocaleDateString()}`, margin, y);
  y += 8;

  if (data.projectName) {
    doc.text(`Project: ${data.projectName}`, margin, y);
    y += 8;
  }
  if (data.notes) {
    doc.text(`Notes: ${data.notes}`, margin, y, { maxWidth: contentW });
    y += 12;
  }

  // ---- Page 2: Single pair analysis ----
  doc.addPage();
  y = margin;

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Color Pair Analysis', margin, y);
  y += 12;

  // Color swatches
  doc.setFillColor(data.fg);
  doc.rect(margin, y, 30, 15, 'F');
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Foreground: ${data.fg}`, margin + 35, y + 10);
  y += 20;

  doc.setFillColor(data.bg);
  doc.rect(margin, y, 30, 15, 'F');
  doc.text(`Background: ${data.bg}`, margin + 35, y + 10);
  y += 25;

  // Contrast ratio
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(`Contrast Ratio: ${formatRatio(data.ratio)}`, margin, y);
  y += 15;

  // WCAG levels
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  const levels = [
    { label: 'WCAG AA Normal Text (4.5:1)', pass: data.wcag.aaNormal },
    { label: 'WCAG AA Large Text (3:1)', pass: data.wcag.aaLarge },
    { label: 'WCAG AAA Normal Text (7:1)', pass: data.wcag.aaaNormal },
    { label: 'WCAG AAA Large Text (4.5:1)', pass: data.wcag.aaaLarge },
  ];

  for (const level of levels) {
    const status = level.pass ? 'PASS' : 'FAIL';
    const statusColor = level.pass ? '#1a7a1a' : '#c0392b';
    doc.setTextColor(statusColor);
    doc.text(`${status}`, margin, y);
    doc.setTextColor('#333333');
    doc.text(`  ${level.label}`, margin + 12, y);
    y += 8;
  }

  // ---- Page 3: Colorblind descriptions ----
  doc.addPage();
  y = margin;

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor('#333333');
  doc.text('Colorblind Simulation Notes', margin, y);
  y += 12;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const cbDescriptions = [
    { type: 'Protanopia (Red-Blind)', desc: 'Affects ~1% of males. Red appears dark/muted, reduced ability to distinguish red-green.' },
    { type: 'Deuteranopia (Green-Blind)', desc: 'Affects ~1% of males. Green appears muted, difficulty distinguishing red-green hues.' },
    { type: 'Tritanopia (Blue-Blind)', desc: 'Affects ~0.001%. Blue-yellow confusion, blue appears greenish.' },
    { type: 'Achromatopsia (Monochrome)', desc: 'Very rare. Complete color blindness — sees only shades of gray. Contrast ratio is the primary indicator.' },
  ];

  for (const cb of cbDescriptions) {
    checkPage(20);
    doc.setFont('helvetica', 'bold');
    doc.text(cb.type, margin, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    doc.text(cb.desc, margin, y, { maxWidth: contentW });
    y += 12;
  }

  // Footer on last page
  const pageH = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor('#888888');
  doc.text('Generated by accessibilitycolor.com \u2014 Caladan Digital LLC', margin, pageH - 10);

  // Trigger download
  doc.save(`accessibility-report${data.projectName ? '-' + data.projectName.replace(/[^a-zA-Z0-9-_]/g, '').toLowerCase() : ''}.pdf`);
}
